[package]
name = "btoi"
version = "0.1.1" # remember to update html_root_url
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
license = "MIT/Apache-2.0"
keywords = ["conversion", "integer", "atoi"]
readme = "README.md"
repository = "https://github.com/niklasf/rust-btoi"
categories = ["parsing"]
description = "Parse integers directly from byte slices"

[[bench]]
name = "benches"
harness = false

[badges]
travis-ci = { repository = "niklasf/rust-btoi" }

[dependencies]
num-traits = "0.1"

[dev-dependencies]
quickcheck = "0.5"
bencher = "0.1"
